services:

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - projectyear3-network

  gateway:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      # - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - projectyear3-network

  frontend:
    image: projectyear3/frontendyear3:latest
    restart: unless-stopped
    networks:
      - projectyear3-network
    expose:
      - "3000"
  #   build: ./frontend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost/api

  backend:
    image: projectyear3/backendyear3:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    
    # deploy:
    #   replicas: 3
    networks:
      - projectyear3-network

networks:
  projectyear3-network:
    driver: bridge
