services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      # - frontend
    networks:
      - projectyear3-network
      # - frontend-network

  # frontend:
  #   build: ./frontend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost/api

  backend:
    image: projectyear3/backendyear3:latest
    # deploy:
    #   replicas: 3
    env_file:
      - .env
    networks:
      - projectyear3-network

networks:
  projectyear3-network:
    driver: bridge
