events {
    worker_connections 1024; 
    }

http {
    upstream backend-api {
        server backend:3000;
    }

    # upstream frontend-nextjs {
    #     server frontend:3000;
    # }

    server {
        listen 80;
        server_name teamproject.rltg.online; 

        location /api {
            proxy_pass http://backend-api;
            proxy_set_header Host $host;
        }

        # location / {
        #     proxy_pass http://frontend-nextjs;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}