name: Deploy to server

on:
  repository_dispatch:
    types: [update-frontend, update-backend]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest images
        run: docker compose pull

      - name: add env variables
        run: |
          echo "TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }}" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "COOKIE_SECURE=${{ secrets.COOKIE_SECURE }}" >> .env
          echo "COOKIE_SAMESITE=${{ secrets.COOKIE_SAMESITE }}" >> .env
          echo "SESSION_MAX_AGE_DAYS=${{ secrets.SESSION_MAX_AGE_DAYS }}" >> .env

      - name: Restart containers
        run: docker compose up -d --remove-orphans 

      - name: Cleanup old images
        run: docker image prune -f