name: pull main branch
on:
  push:
    branches: [main]

jobs:
  pull-and-update:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/githubactions/deploy-year3

          git pull origin main

          echo "TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }}" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

          docker compose up -d --remove-orphans

          docker image prune -f
